# Generated by Django 5.2.3 on 2025-08-10 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kebele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebele_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('plot_size', models.FloatField(help_text='Size in hectares')),
                ('soil_type', models.CharField(choices=[('vertisol', 'Vertisol (Black Cotton Soil)'), ('cambisol', 'Cambisol (Brown Soil)'), ('luvisol', 'Luvisol (Red Soil)'), ('nitisol', 'Nitisol (Red Clay)'), ('andosol', 'Andosol (Volcanic Soil)'), ('fluvisol', 'Fluvisol (Alluvial Soil)')], max_length=20)),
                ('irrigation_available', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
