# Generated by Django 5.2.3 on 2025-08-10 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_kebele_landdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetail',
            name='kebele_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to='user.kebele'),
        ),
    ]
