# Generated by Django 5.2.3 on 2025-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_landdetail_kebele_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('sorghum', 'Sorghum'), ('rice', 'Rice'), ('bean', 'Bean'), ('lentil', 'Lentil'), ('safflower', 'Safflower'), ('sesame', 'Sesame'), ('soybean', 'Soybean'), ('carrot', 'Carrot'), ('garlic', 'Garlic'), ('onion', 'Onion'), ('tomato', 'Tomato'), ('mandarin', 'Mandarin'), ('mango', 'Mango'), ('coffee', 'Coffee'), ('avocado', 'Avocado'), ('banana', 'Banana')], max_length=30)),
                ('quantity', models.FloatField(help_text='Quantity required in tons')),
                ('price_per_kg', models.FloatField(help_text='Price per kg in ETB')),
                ('harvest_date', models.DateField()),
                ('region', models.CharField(max_length=50)),
                ('quality_requirements', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
