# Generated by Django 5.2.3 on 2025-08-10 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_croprequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerExporterMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=30)),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('crop_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='user.croprequirement')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exporter_matches', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_matches', to=settings.AUTH_USER_MODEL)),
                ('land_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='user.landdetail')),
            ],
        ),
    ]
