# Generated by Django 5.2.3 on 2025-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KebeleCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebele', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('seasonal_rainfall_total', models.FloatField()),
                ('onset_date', models.FloatField()),
                ('cessation_date', models.FloatField()),
                ('rainy_days_count', models.FloatField()),
                ('dry_spell_days', models.FloatField()),
                ('onset_delay_days', models.FloatField()),
                ('onset_threshold', models.FloatField()),
                ('rainy_day_threshold', models.FloatField()),
                ('dry_spell_threshold', models.FloatField()),
                ('rainfall_std_dev', models.FloatField()),
                ('rainfall_skewness', models.FloatField()),
                ('mean_soil_moisture', models.FloatField()),
                ('dry_soil_days', models.FloatField()),
                ('dry_threshold', models.FloatField()),
                ('soil_moisture_std', models.FloatField()),
                ('mean_temp_season', models.FloatField()),
                ('max_temp_avg', models.FloatField()),
                ('min_temp_avg', models.FloatField()),
                ('gdd_total', models.FloatField()),
                ('gdd_base_temp', models.FloatField()),
                ('heatwave_days', models.FloatField()),
                ('heatwave_threshold', models.FloatField()),
                ('ndvi_peak', models.FloatField()),
                ('ndvi_scale', models.FloatField()),
                ('ndvi_seasonal_avg', models.FloatField()),
                ('ndvi_start_of_season', models.FloatField()),
                ('ndvi_end_of_season', models.FloatField()),
                ('ndvi_integral', models.FloatField()),
                ('ndvi_threshold', models.FloatField()),
                ('ndvi_anomaly_avg', models.FloatField()),
            ],
        ),
    ]
